package agent

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SaveConfig writes the configuration to workspace/data/config.toml
func SaveConfig(workspace string, cfg Config) error {
	path := filepath.Join(workspace, "data", "config.toml")

	// Create data directory if not exists
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Ni Bot Configuration\n")
	sb.WriteString("# Generated by Web Interface\n\n")

	if cfg.Provider != "" {
		sb.WriteString(fmt.Sprintf("provider = \"%s\"\n", cfg.Provider))
	}
	if cfg.BaseURL != "" {
		sb.WriteString(fmt.Sprintf("base_url = \"%s\"\n", cfg.BaseURL))
	}
	if cfg.ModelName != "" {
		sb.WriteString(fmt.Sprintf("model = \"%s\"\n", cfg.ModelName))
	}
	if cfg.APIKey != "" {
		sb.WriteString(fmt.Sprintf("api_key = \"%s\"\n", cfg.APIKey))
	}
	if cfg.LogLevel != "" {
		sb.WriteString(fmt.Sprintf("log_level = \"%s\"\n", cfg.LogLevel))
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

// SaveToolPolicy writes the policy to workspace/data/policy.toml
func SaveToolPolicy(workspace string, p ToolPolicy) error {
	path := filepath.Join(workspace, "data", "policy.toml")

	// Create data directory if not exists
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Ni Bot Policy Configuration\n")
	sb.WriteString("# Generated by Web Interface\n\n")

	// Global Switches
	sb.WriteString(fmt.Sprintf("allow_fs_write = \"%t\"\n", p.AllowFSWrite))
	sb.WriteString(fmt.Sprintf("allow_runtime_exec = \"%t\"\n", p.AllowRuntimeExec))
	sb.WriteString(fmt.Sprintf("allow_skill_exec = \"%t\"\n", p.AllowSkillExec))
	sb.WriteString(fmt.Sprintf("allow_skill_install = \"%t\"\n", p.AllowSkillInstall))
	sb.WriteString(fmt.Sprintf("allow_memory = \"%t\"\n", p.AllowMemory))

	sb.WriteString("\n# Approval Requirements\n")
	sb.WriteString(fmt.Sprintf("require_approval_fs_write = \"%t\"\n", p.RequireFSWrite))
	sb.WriteString(fmt.Sprintf("require_approval_runtime_exec = \"%t\"\n", p.RequireRuntimeExec))
	sb.WriteString(fmt.Sprintf("require_approval_skill_exec = \"%t\"\n", p.RequireSkillExec))
	sb.WriteString(fmt.Sprintf("require_approval_skill_install = \"%t\"\n", p.RequireSkillInstall))
	sb.WriteString(fmt.Sprintf("require_approval_memory = \"%t\"\n", p.RequireMemory))

	// Lists
	if len(p.AllowedRuntimePrefixes) > 0 {
		sb.WriteString(fmt.Sprintf("allowed_runtime_prefixes = \"%s\"\n", strings.Join(p.AllowedRuntimePrefixes, ",")))
	}
	if len(p.AllowedWritePrefixes) > 0 {
		sb.WriteString(fmt.Sprintf("allowed_write_prefixes = \"%s\"\n", strings.Join(p.AllowedWritePrefixes, ",")))
	}
	if len(p.AllowedSkillNames) > 0 {
		sb.WriteString(fmt.Sprintf("allowed_skill_names = \"%s\"\n", strings.Join(p.AllowedSkillNames, ",")))
	}
	if len(p.AllowedSkillScripts) > 0 {
		sb.WriteString(fmt.Sprintf("allowed_skill_scripts = \"%s\"\n", strings.Join(p.AllowedSkillScripts, ",")))
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
